name: on-release-published

on:
  release:
    types: [released]

jobs:
  on-release-published:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Prepare build
        run: |
          corepack enable
          yarn install --immutable
          yarn build
        env:
          CI: true
      - name: Publish to NPM
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "No NPM token"
          else
            yarn config set npmAuthToken "$NPM_AUTH_TOKEN"
            yarn npm publish --access=public
          fi
        env:
          CI: true
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload new docs
        id: upload-docs
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
  deploy-docs:
    needs: on-release-published
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.upload-docs.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy new docs to Github Pages
        id: deploy-docs-step
        uses: actions/deploy-pages@v4
